
title: Kado
description: >-
  A design oriented HTML, CSS, and JavaScript library.
baseurl: ""
url: "https://kadocss.com"
twitter_username:
github_username:  paper-krane

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"

    -
        scope:
            path: "docs"
            type: "pages"
        values:
            layout: "documentation"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
